rm -rf /var/lib/ambari*
rm -rf /usr/lib/ambari-*
rm -rf /etc/ambari-*
rm -rf /etc/hadoop
rm -rf /etc/hbase
rm -rf /etc/hive 
rm -rf /etc/oozie
rm -rf /etc/sqoop 
rm -rf /etc/zookeeper
rm -rf /etc/flume 
rm -rf /etc/storm 
rm -rf /etc/hive-hcatalog
rm -rf /etc/tez 
rm -rf /etc/falcon 
rm -rf /etc/knox 
rm -rf /etc/hive-webhcat
rm -rf /etc/kafka 
rm -rf /etc/slider 
rm -rf /etc/storm-slider-client
rm -rf /etc/spark
rm -rf /var/run/spark
rm -rf /var/run/hadoop
rm -rf /var/run/hbase
rm -rf /var/run/zookeeper
rm -rf /var/run/flume
rm -rf /var/run/storm
rm -rf /var/run/webhcat
rm -rf /var/run/hadoop-yarn
rm -rf /var/run/hadoop-mapreduce
rm -rf /var/run/kafka
rm -rf /var/run/ambari-metrics-*
rm -rf /var/log/hadoop
rm -rf /var/log/hbase
rm -rf /var/log/flume
rm -rf /var/log/storm
rm -rf /var/log/hadoop-yarn
rm -rf /var/log/hadoop-mapreduce
rm -rf /var/log/knox
rm -rf /var/log/hive 
rm -rf /var/log/oozie
rm -rf /var/log/zookeeper
rm -rf /var/log/falcon
rm -rf /var/log/webhcat
rm -rf /var/log/spark
rm -rf /var/log/ambari-*
rm -rf /var/log/hive*
rm -rf /usr/lib/flume
rm -rf /usr/lib/storm
rm -rf /var/lib/hive* 
rm -rf /var/lib/hadoop-*
rm -rf /usr/hdp
rm -rf /var/lib/ambari-* 
rm -rf /var/run/ambari-* 
rm -rf /usr/lib/amrbari-* 
rm -rf /etc/ambari-agent 
rm -rf /var/log/ambari-agent 
rm -rf /usr/lib/python2.6/site-packages/ambari*
